---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: protonvpn-secret
  namespace: torrents
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgDQDb9nU3H49WXitUHOiapo/Hrd4AsKhiTHMYoIsuM+PmmSlwikKaHNQ6YVZNsZHosQMlHQ+zIq0s5nmx6vavbKtCciM+rEhPA42SpMYJ7agl6O498KfWmk3tbhP46Rh2C/HKa/MpMTzuQZWszbIFOZWUJig5aYEcdlshfSpU0BT0zr2JmNy9DdYk/ImhYZcVHoiIhSdBD8pcee6DW1d9tHYMETkuj5pbOO2/y4sZslSGXuD7RrV83K4GBag2vp8Wt3Y1R/eBVnUGAwvqCZ7g/AeNjPi/pWVvWsL6LC3IboNakL6oRq4e4RQUMVdUMMKNghT0z1mQUmqdbPsJTLGIiClVgj/3zC+20/Rnq1kCD6mVY8bm9rXai4/eugMkCN+rh55a12kjMpl/9UrU3COeshoL6Q7YTWKJPT2svonaVwAgnZdYcsApoHC32UVxE+2blCXOE2HToy4YjvWnC57+s32+L5D93o/ja9AaHtS6rmjwFHGCLzhiY7ROCPSNrguAxUnWIegJ21iGX/Jw46WjqG4kW3vKEBspjffW8rTbes9LupiXloizsHL+rO6htMHGLUUTAg9cOn8BQqXIInTET10lQRooIQUbZG6shhhchu7PNgCINvsZWTwL85+DCkA0n4mZ1De0oIahJK5OUFp+zXV5S8TH4QDB+G8VFKMrt+UlsEaYCyYLuHzJa5TrBuK+wG8z2G6iu8xBtk6PfjdUNe83Vu5yQHS6hSAGZGFda39kmGBqC39Dfxp4xJrQ==
  template:
    metadata:
      creationTimestamp: null
      name: protonvpn-secret
      namespace: torrents
    type: Opaque
