---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgAdJquWyJkNOi2r2or2w7sb8LPBaPDz/uPsnJLq0OZEeYs3Dz+DiQguOLoO2M1ZnYQIaumWCfdLrAERtV5lyt8AdJUz70VrobWmvco1169IWm61TcAaaFTTzql5h90VDCUSOtT8nlF5irhQcI5H2FPAqGCMJXy1UTNP6tgSxObF9xqfUvL1KzdGJKdeyExWogUhfgHxv3LcZ5LHdk0Z75iKhrTBaBhGptZdC4rgc5z8a5Hk8ale3iLR4B/Og32HevsCOLxjWrwrgPlpTDsvOsL3bWE+2sDGEr+mrpoJE+Idclyci9q6ax5WNn0ir6JbI1IH3mIaP6ODdLev+3i9GQTho/hFdsXX9JbKy5zAA7xGECXw+c7mVyiHTYJWga0fto59VGYbckk2uGGxhxAMRAlLDeECclyZKTx224gVVGuYh144BVM34imUpgr4s4y93Wv+ZSNrzmWw1CnS7aHI+cBJb6PDR0aH1PaIWV36PVnSg7Uldu1WTVy7RP03uB4YrnmDHaL3LI0ipLR2Wdrj7R8Bmnnf6qHQ3GJdWeZWIQxA2F1WfXMzCX7nz5KMIjCBKDQBg93TaNsvGUzqVgFPtehrlP/u9wNWMe5v7UC7WYB8GRYMvWm4W+YfBCQ4G0hBWNLxCrWGtYYpH2Ekyyw4GPhHmWSdgH8JUwv3EEl5KJjZpaC2kqG6o0xwndPWqgy8F9KwQXMb/9hF8A0jVT9tz1vybNE7ww8DJtDrurblveqx3GfB74NATOHF3Xqooykq3jwzGV62zqUHvWhIbrHE
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
