---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgBrWWjtXAZDXbLm9W6ofn3CRXb2vEODP4d9XJoXXlRmyAVugrLkdBAKnJyYeeKk7VHKL3A1VGqbigC3v/YXJsNkkwDo2/PoB/bddMmZBLV3nXxqBylhEfClfELspqP9cxH0xOgvOMvivUP3FTAw7QIn/ZmWYpoxRw6cWEfrjDMxPtNC6OWFD+QD786U3+DOLbfq74RkGROtuD30m9882q2aa00WOcnoSZgLQ7h1ENjCmJjiB6Mcj2GX85XCm1jWaj4z1OfVlA1jvDhE8lUQDJsqfXS3z/6JB33kNJkYvulRD901sfR9stS5sb0uoK9uoTlZXiqyHRnE2vRNX0myubKEouOqLQhkHQWWp8DSOM5bDS7tQ0wTrdmhJqtt8KigmzOXa9W0oklaqF68NawQRotKYfzV8494YmLzAgu0uOhQLjwA4HjyWo6aO2XltL5pSKAe+Z2YZGLLXyt1xirrmbEP0jbqPEtw3GsEUImIQuVUAmleH4l0UM5+WFZDZeDoVnjwahpRy0pMnnMAj3zKRnZiFRqN5Qi6qCFSwhTF39u9R0u6M5hjfrD7q/w9B5MAUgBQLfNDgyYxt362eNHCHulT45K7wM9gWZnzqsR5U1OnI9qEssUCz4IyGwIz5SFMxAY+Tai17t/zdZFk+gAF9fvmKmJxYDQnPlpV6XlFfV4I2zqqQqxwMS8qtAsid0IBbYzjzfTNYqoFOFgyujh0bqoVN7fmXZLlhXktIFBrQK/QXYQF04TXBvrokyc8aPS+S/bsoG0q/paQjxocWjTL
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
