---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAM2JmxNgTq/mtU5i5cpX2oEmSXvJtet2JzBUBIx0DOTbX1nzE1YuLp9Xc0x3BmfiTpkHVs1qKSd2xeCjRtmQocEYrOpfEeW1eVQS1+mpOP7yOjCi3CXtYaHdkXhAwUuyMeupCoflK/qJ/RyN+4moDqfEDlDtryLTwKfrSG5eKVrmv4UuCQJSVvpcqggiTE+MrNsTO+m2chqfbD4cC9O6QTkajkYGPQ7xVEaVPlk8K42DRrtVV7IU2IVO4prM8IvESqSHp7vFUa0Wd8pw1HopNrQRp4gY/ieaqqkPEfaOPCjLPLjXU/04CbuHzWYOiKttczfzbQUOvZK/0BiDcGkpQ/IqPkfhDJqv7zhs/LsMiyex2nXqfV8AAXAUuMI5fQFzYDzKaT5KgMqrFlBm4931t+MfNe95ZqS9mq1PV7pHt+Wyhtlmt1p4ACZ2gGSVxyzvhOGzSFWqCI2vky63m/sFI2N6v23imS581AwV2cosB94AQkU+Qnhxqj6BftmqQM4FFF+ZDThSFdsD+2U4Tuk049YARMjNk6fg69WVGv3T5Cc7AKetxIiu/RtuDIv/emUdpKWjezuQVh6EXwcbza2m1QLaAk8A4gutSEuvZdKVCByg7zPHtiCtk8ObDehEGo+4yGrDyi9GjXBewt4+vLUhZx8vesxkDfyJikyGN22YA6UWU4q1GXWKy6onUdUQzWSWEooqHO1M5/oXQ=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
