---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBtnHWASJmLj43D949XNdENOljrTqYuLiWgDRUk8xLOlELPSomI4C1YU4xfIsX2SOFmNrGQRdXkG2h/6YqXO6E6cHjb77w3SGAwzO+TUmY2EUsUTH94zMypeqnwvuhYgFUi/WCtfE2sueH/HrvCR/BquJ7nZNgfQwJ5N0ArmoG3Jye+yGwxHu4lESEESGCPhzoGUGaTh+2AgBHVb2jUDcRBcjqiWJ0lRH/hmHMNnclCHTZzHV4nHywUFK2JZkmElFTbO2bMMQdcj1njFclvEH3hfQqSkCP8cQe6SF1KkKLHA+G9AOhofu98jw08JEvU6vt+1cXnM0nDHtswGYNUILOl7g/ivGgG88em41YxIv4pgMvtKkv9JJVQjD2wObPUaK9+PA8swZsaiHHuXC5VnKqKQaDXqpXGWKa7X8mD1pAyy5x+wLejAQA7IMDpkCcchgRj+gKdhDGS6/kIznIJGmzPqeLJGEG7if+JDLHEkYfRjn/O33FTOT2aXxtSHmU/dXLmOwsX4qnY9lLc4bCavl+QHHuBF5fJTxY1JrsC1EnL1hbep4Ah7Zzqs6IoVM4hOW+LTfLmUfaDV7HJsMGKxdSPUvTnsitE3r9S2qmABSEmQLXX3xbpXTulvBzBqwRQ1Rzr5WIHMlK0OFXSMaI8bgqy8f2dWI+Dqvefny/qLw97ogBtBrPsDWscYXnvxdrsI8CcmcevC6IU5B0=
    admin-user: AgBRDQeuhcaMHc3pSL5ih055PHhdV28l91TByA2nYDHW/Bdk5olRB55fNu1M45Hx2VaWxh2W70bj/Et9UZZ7yNtD/AkL3vlG5F2xESU5HB7CdpEftnGu3iQmcwfWXYOXmOcqXs1GwnzS5+aGp1Wefr0doYuLj1ruzfOyIYFu6SRljS5VZkW6uDhRrouxG9+YyFSpaB902GagTug5q+UG10or5NojgpYZv4pGcBUdH+3hrMYKXThkiRtdEaFqMhLy19icedfkpl6jO6bSVKe+0Cno9vgI0MdbcPP8ggmuHekUKqoRG5cpiUFsmIgglAO/7DgDCHQL7yMkz+/9mp1xaCN7HygXU+aXeu4oAIG6UQFrLQhdT7+eGEhaNuFcp5i2JnNZoCvUesn/2wKUwWEZjTsTCNoInLCDxBHCAsJ4/moAM6XKCPj9LrVjLf25IhazWGCvAO2Rz3Y7BQCeMj8+yLVcBrj6SIjYeNv3ZOrZIu2L/DRVrPnZnJmUR/G0Lz6s+D71mZW9cUH/quOCvnRmBePhmXYNSJFvK2dUFrBNEyRoVTmPsWVTbOkeJTe55B1mTVatA1fDM2bzJLcQVnAN1g+MTMRpe/bJ54AIRhHBKHhAL20naH8QEyLRBuQPLJWHq5IFjZDn7Zu+AJ+vGlijEdLgJJghzkbXxCK2zUDQW486S87yroxZ7jYE6ujNFzF1t+kmdBwsKQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
