apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: https://ntfy.jklu-lab.eu
    upstream-base-url: https://ntfy.sh
    auth-file: /var/lib/ntfy/user.db
    auth-default-access: deny-all
    behind-proxy: true
    cache-file: /var/cache/ntfy/cache.db
    cache-duration: 12h