---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAqq+fdoXdSoDyFV21glcLNRlzUhHJM8E5bnOSM7FSoS4tZz2/vphGiqhDPhbr09estxmbIsUKOao+zULyKhIFu34QIV6H80OxtFSjzF7CHuDP5KtBHzQF/JteOijLpT1lr8FKvuJoQpQkNNQTgeWHj8KGVUwRD9GsKnKnebQi542k6yXnqoKAdXxB45OYiqCo1QMNsG0rJdYJJSEM2qh12QLkR22xdyASnJXbVzKraHvQVL4ONwBzVoOvZWWJZ2vWk0KVQnTPdP3zXQICRnJYaSSmhIhNAEh0PyTL/fkXKVqopRlQDB6VGat2hq1PZpulrej17JKbKSaSbdu09Ucsrz0CV/ZBI1NqT3jOppVdTHvuJNXl7MsJXiCYa+s4ht1J7LUsOgwgOs5q/w74nAROKt2mJ0Ty94A0JlXV7NdZbi+N8UTH9DrP4S9OaxKFGvqTXmQjuu+oqS5hk7lt7RnxWSui5Q2EipNmoIWuMrFhnlSbvTVdb28V+JaTcBko0fputzIYwyRcZSGp874i3RhFR1zwXT3/BXfwaICqSEoTvuxBCHk1UkldVQQyJjrqLZByM9ueFwzywxGZA+oyPNpMmvWDT1bniac3dB79YjT8oUC56bZR5F667//0yue2p4K656TCV+vfZ7GtNXySgk6BdjwvZvBn8YqvLTtBQnn9gAY8oAKl5O3SpqWKG6yfCh9Ap28wcug9CdwUaRyxADMcNzkM/Q0kmuzK3kdNkGTV0wNRou0YPpyGzHYfi3AaTkk0if/L8dg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
