---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgApTg1nIhctWVd3+8Q9FQwN20J9U4ESx5tYvObqBceKHCtzZmNRKj3uaKvUdBARC1YK73qy0KaccHzvlE5dR+qMxX1Z/nPXzi66bK6Z10k7+74wkpVpfRAs4jUz6CVOdL8KYsJj5OrscJTzrobzJj0syRaE/lhR3HDZlTxxh3dJilOt948Q0vZ3YFXNgPIkkpbpp3kC1byL0IV7imGNNSVWuyY/nyJFoAug6ohfP89FOpRMgSU48go0scE/uwhjZ/uvh2h3nxFAG9HdJ6LxO6kRT+JEopSaTp2aTkguBAHPBxXZq5bgNQSwEZQnFvdB7gbhgg5muWBuDsiRwWNrwk2ZqPHTMxqCMBiLpcHQ8VKi1s/UFksZ8mHdVYelJUWc6CHRMkxlB2SxPq877WZjCVsG5yaiQZmTJLVGtoYQrAWDOgF9lGmKof6VzWExd0/YIa8OcTAT5DcdN+J5NRpNk/QVmHU9JtCS8cWb7XhxhhHZYgcwGtXDm6vNninvfE64EHtIbZ1UEP3NqBlefRvl8FujW5POYE//X/YZc1CMfNgHfi63LVN5fbGJwMDGc9F7yIY8RhqL0pGP2twgsajA/R6pjVJAdnYVUiCgUa5qsHNbzK0ViKKt+2MgIx+N78WDxFQvGyelW+RasHe7vnuddUMa8Nn7vpoCTJlOygyx58zaSykuLzqHAQ1wlC0RYFiSgSJOtywUGm0zIiEp0mG+uBQm+CXKnzl10sH6uQu0dQl3VdXH0ZrAvhNsUkFVv6CRhRMbYuZBlA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
