apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/JKlucka/homelab.git
    targetRevision: HEAD
    path: infrastructure/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: immich-redis
      namespace: media
      jsonPointers:
        - /spec
    - group: apps
      kind: StatefulSet
      name: immich-postgres
      namespace: media
      jsonPointers:
        - /spec