apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: torrents
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/JKlucka/homelab.git
    targetRevision: HEAD
    path: infrastructure/torrents
  destination:
    server: https://kubernetes.default.svc
    namespace: torrents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true