---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-secrets
  namespace: media
spec:
  encryptedData:
    DATABASE_URL: AgCSc/99LjyxodwuE9E5/YVDajG59OGMJEtay2R0g2ntZ2nEz+CAoclzj+RVQiMPxsIMQKFBYqleOIzCwxymmIbxu5Wx7G9rUR6v9aFF3d7c9atMULBCa4VVLqtdAXfSkg1GqLzHF1q49E+CWticjuEI1eDHBFFvesAAs68bSfIbJsjc75r/t48LPdirHO09BbKUeBcnfkOYvTvnRvPfBqdw0HIfh/FJv7g9iORcvh9efbmnEVsurJcKb3dJSPIi6RtwM5NYqh0REudHi5uIKxgtADYHQZvm8uwBx10bYhFoiP8NVv2+tsDXBVPEeZmYqP7gYOKb7ojH+Wirt1e1PsGs03HeWLYHUDTXVrqmPhFIKaHZoQeVt2ExNbyDE9AGAu2KdfcJMNkApUhbMDz9RwenuyARI9N/W7M5fl4saswiw3Pqkf1Y/NFEZUMPWqQjgYtVAxhrS8cu20wGDnrh6uoae1FTudfHws9gZvbpQ+Dnnig4o+ED/vfEx00FVS58gDuT+G/XWcwEuDJSahQwMfnwFfpMu9fHRnrmkX5zHQLgGtV7A2wZE0x1s8Bc5odU/J6+RV69OaNuh3HdAWGgYO73+nBgwaFYPxTFv5/9EEP7znv1SJulsxPKcjOSm9QbPF8kyXafU/wTAXufZ84mqYht9ygpLV56JS1r+DfLxgOcPrunImqugj+lznmt0sHj8iawMNkIKS5I4KC6Gm+6x/CkZQZhIkl+ghdujxcXrgY4BCdvqx2OxdSokXuZxUWNVw==
    REDIS_HOSTNAME: AgDC6M2Nhkq4SdcqSa/sLr61xC5fXUiAhTkRL7JTyANX5C1JBB3k0+UHJj57beR8dU3Ahuu1aoNwcJJrUnvj3vDwNKo4VSSc+053Yh1Ekj9uwiGFFVmoGDRcf1RqWfUhEQMI+0FmXT+pOcu2SdseKvwqR0PF4GfeQQSnvubE3OiUeNdqwfjZZSIVOG0P6mw4rlasxnAEaOTAZxDcnwYL4No+M32ZLWm098rzYZbT8DBe/0tIhUeWKwwf7UmU65tSI8pUR+yLRAXG99Aa69FbrTn5icsQWl8ILWsXrslf19kiITu1l2SjQHy/RuW+DeQEA5z99G416ggl4UoyilnTSqGXxhK1U4keif6rNWG4QjAfXLVqFi18Ri6eqMU5rwiI4Dn/eUHMyisgLVSQyqITAzNEBYO3yN8A9eCnC/Fe9guD/3h7KMFlG3F/tip31ksEujB4jYbD4IAXUb1gj045BnqcgxtGx7sCfkmsrDHG6L2eSYK4mHjFd1yUyvddEfMfmhiIkwlzkhZcwduiMRNkxuJy8qcgWj+VSMjCEQ4v7kxb0YQBCpGJ2/U8o70nqc6P3FIKxRYg7uHf0/0j+1qEExWFT86IW2/A6MlyAXyr2QvkQ5SYNm3H4D7WjMefjLUQSgryEl7waBd1Q6VCbHGtUALeoylziq4Fs7q9B+pvDpdWWUHXqf7GaENFymEA/rT13Ipco1fcPfhhbeGSv2C6
  template:
    metadata:
      creationTimestamp: null
      name: immich-secrets
      namespace: media
    type: Opaque
